import express from "express";
import pg from "pg";

var cloudinary = require("cloudinary").v2;

const app = express();

var fs = require("fs");
var cloudinary = require("cloudinary").v2;

var uploads = {};

cloudinary.config({
  cloud_name: "austaino",
  api_key: "835634458346263",
  api_secret: "79yg13obCA51riaUv-q6K67SFGs"
});
console.log("** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");
cloudinary.uploader.upload("pic1.jpg", { tags: "basic_sample" }, function(
  err,
  image
) {
  console.log();
  console.log("** File Upload");
  if (err) {
    console.warn(err);
  }
  console.log(
    "* public_id for the uploaded image is generated by Cloudinary's service."
  );
  console.log("* " + image.public_id);
  console.log("* " + image.url);
});

var conString =
  "postgres://umujzzme:5fZi1FGtyH0f5VL73o6CKWbus5YCsq7e@salt.db.elephantsql.com:5432/umujzzme";
var client = new pg.Client(conString);
client.connect(function(err) {
  if (err) {
    return console.error("could not connect to postgres", err);
  }
  client.query('SELECT NOW() AS "theTime"', function(err, result) {
    if (err) {
      return console.error("error running query", err);
    }
    console.log("connected to database");

    //client.end();
  });
});

const port = process.env.PORT || 3000;

app.get("/", (req, res) => {
  res.send("Hi Prospecting Andelans Hello API this is DevC");
});

app.listen(port, () => console.log(`Server running on port ${port}`));
